/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/Alert.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    FormItem: typeof import('./src/components/Form/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    Switch: typeof import('./src/components/Switch/Switch.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip/Tooltip.vue')['default']
  }
}
